config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :price_registers
  resources :sales
  resources :products
  resources :categories
  resources :rotations
  resources :employees
  resources :stalls
  resources :departments
  resources :phone_numbers
  resources :branch_offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'branch_offices#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
         can
       else
         can :read, :all
         

       end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
    has_many :phone_numbers
    has_many :rotations
    has_many :products
    
    validates :address, :uniqueness => true, :presence => true
    paginates_per  6
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :category_name, :uniqueness => true, :presence => true
    def categoriaPadre
        if id_category_father.nil?
            "No tiene categoria padre"
    
        end
    end
    paginates_per  6
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :rotations

    validates :department_name, :uniqueness => true, :presence => true
    paginates_per  6
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :rotations

    validates :document_number, :uniqueness => true, :presence => true
    validates :gender, :presence => true

    def full_name 
      first_name + " " + last_name
    end
    def sexo 
        if gender == 1
          "Masculino"
        else 
          "Femenino "
        end
    end

    paginates_per  6
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :branch_office
  validates :phone_number, :uniqueness => true, :presence => true
  paginates_per  6
end

app/models/price_register.rb
class PriceRegister < ApplicationRecord
  belongs_to :product

  paginates_per  6
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :branch_office
  belongs_to :category
  has_many :price_registers
  has_many :sales
  
  validates :product_name, :presence => true
  paginates_per  6
end

app/models/rotation.rb
class Rotation < ApplicationRecord
  belongs_to :branch_office
  belongs_to :department
  belongs_to :stall
  belongs_to :employee
 
  
  def jefe
    if head == true 
      "YES, head of stall"
    else
      "NO, head of stall"
    end
  end

  paginates_per  6
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product

  paginates_per  6
end

app/models/stall.rb
class Stall < ApplicationRecord
    has_many :rotations

    validates :stall_name, :uniqueness => true, :presence => true
    paginates_per  6
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rotations_helper.rb
module RotationsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stalls_helper.rb
module StallsHelper
end

app/views/shared/_language_switcher.erb
<% if I18n.locale == I18n.default_locale %>
  <%= link_to "Change to English", { :locale=>'en' }, class: "btn text-dark" %>
<% else %>
   <%= link_to "Cambiar a Español", { :locale=>'es' }, class: "btn text-dark" %>
<%end%>

app/views/shared/_main_menu.html.erb
<div class="collapse navbar-collapse show" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to t('e.index'), root_url, class: 'btn-primary nav-link text-white  h6' %>
    </li>
    <% if user_signed_in? %>
      <% if current_user.admin? %>

      <li class="nav-item">
        <%= link_to t('e.price_registers') , price_registers_url, class: 'btn-primary nav-link text-white h6' if can? :manage, PriceRegister %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.sales') , sales_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Sale %>
      <li class="nav-item">
        <%= link_to t('e.products') , products_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Product %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.categories') , categories_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Category %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.rotations') , rotations_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Rotation %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.employees') , employees_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Employee %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.stalls') , stalls_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Stall %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.departments') , departments_url, class: 'btn-primary nav-link text-white h6' if can? :manage, Department %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.phone_numbers') , phone_numbers_url, class: 'btn-primary nav-link text-white h6' if can? :manage, PhoneNumber %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.branch_offices'), branch_offices_url, class: 'btn-primary nav-link text-white h6' if can? :manage, BranchOffice %>
    
    
    <% else %>


      <li class="nav-item">
        <%= link_to t('e.price_registers') , price_registers_url, class: 'btn-primary nav-link text-white h6' if can? :read, PriceRegister %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.sales') , sales_url, class: 'btn-primary nav-link text-white h6' if can? :read, Sale %>
      <li class="nav-item">
        <%= link_to t('e.products') , products_url, class: 'btn-primary nav-link text-white h6' if can? :read, Product %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.categories') , categories_url, class: 'btn-primary nav-link text-white h6' if can? :read, Category %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.rotations') , rotations_url, class: 'btn-primary nav-link text-white h6' if can? :read, Rotation %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.employees') , employees_url, class: 'btn-primary nav-link text-white h6' if can? :read, Employee %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.stalls') , stalls_url, class: 'btn-primary nav-link text-white h6' if can? :read, Stall %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.departments') , departments_url, class: 'btn-primary nav-link text-white h6' if can? :read, Department %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.phone_numbers') , phone_numbers_url, class: 'btn-primary nav-link text-white h6' if can? :read, PhoneNumber %>
      </li>
      <li class="nav-item">
        <%= link_to t('e.branch_offices') , branch_offices_url, class: 'btn-primary nav-link text-white h6' if can? :read, BranchOffice %>
    <% end %>
    <%end%>

   
   
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>">Walmart</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= render 'shared/main_menu' %>
  
    <%= render 'shared/user_menu' %>
    
  </div>
</nav>

app/views/shared/_user_menu.html.erb
<div class="collapse navbar-collapse show text-end" id="navbarWithDropdown">
  <ul class="navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle btn btn-primary " href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span style="color:white"><strong><%= current_user.last_name.upcase %>, </strong><%= current_user.first_name %></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
          <li><%= link_to "Editar Perfil", edit_user_registration_path, class: "btn text-white" %></li>
          <hr>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path, class: "btn text-white",  method: :delete  %></li>
        </ul>
      </li>
    <% else %>
      <%= link_to "Iniciar Sesión", new_user_session_url, class: 'btn btn-dark  text-white' %>
    <% end %>
  </ul>
</div>