config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :price_registers
  resources :sales
  resources :products
  resources :categories
  resources :rotations
  resources :employees
  resources :stalls
  resources :departments
  resources :phone_numbers
  resources :branch_offices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'branch_offices#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
         can
       else
         can :read, :all
         

       end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
    has_many :phone_numbers
    has_many :rotations
    has_many :products
    
    validates :address, :uniqueness => true, :presence => true
    paginates_per  6
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :category_name, :uniqueness => true, :presence => true
    def categoriaPadre
        if id_category_father.nil?
            "No tiene categoria padre"
    
        end
    end
    paginates_per  6
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :rotations

    validates :department_name, :uniqueness => true, :presence => true
    paginates_per  6
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :rotations

    validates :document_number, :uniqueness => true, :presence => true
    validates :gender, :presence => true

    def full_name 
      first_name + " " + last_name
    end
    def sexo 
        if gender == 1
          "Masculino"
        else 
          "Femenino "
        end
    end

    paginates_per  6
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :branch_office
  validates :phone_number, :uniqueness => true, :presence => true
  paginates_per  6
end

app/models/price_register.rb
class PriceRegister < ApplicationRecord
  belongs_to :product

  paginates_per  6
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :branch_office
  belongs_to :category
  has_many :price_registers
  has_many :sales
  
  validates :product_name, :presence => true
  paginates_per  6
end

app/models/rotation.rb
class Rotation < ApplicationRecord
  belongs_to :branch_office
  belongs_to :department
  belongs_to :stall
  belongs_to :employee
 
  
  def jefe
    if head == true 
      "YES, head of stall"
    else
      "NO, head of stall"
    end
  end

  paginates_per  6
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product

  paginates_per  6
end

app/models/stall.rb
class Stall < ApplicationRecord
    has_many :rotations

    validates :stall_name, :uniqueness => true, :presence => true
    paginates_per  6
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_phone_number, only: %i[ show edit update destroy ]

  # GET /phone_numbers or /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
    @phone_numbers = @phone_numbers.where(:branch_office_id => params[:branch_office_id]) unless params[:branch_office_id].blank?

    @phone_numbers = @phone_numbers.where(["phone_number LIKE :filter", :filter => "%" + params[:filter] + "%"]) unless params[:filter].blank?

    @phone_numbers = @phone_numbers.order(:phone_number).page(params[:page] || 1)
  end

  # GET /phone_numbers/1 or /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers or /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: "Phone number was successfully created." }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1 or /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: "Phone number was successfully updated." }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1 or /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: "Phone number was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_number_params
      params.require(:phone_number).permit(:phone_number, :branch_office_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rotations_helper.rb
module RotationsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/stalls_helper.rb
module StallsHelper
end

app/views/phone_numbers/_form.html.erb
<%= form_with(model: phone_number) do |form| %>
  <% if phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
        <% phone_number.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-control">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="form-control">
    <%= form.label :branch_office_id %>
    <%= form.collection_select(:branch_office_id, BranchOffice.all, :id, :address) %>
    
  </div>

  <div class="actions form-control">
    <%= form.submit %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<button type="button" class="btn btn-outline-info"><%= link_to t('g.show'), @phone_number, class: "btn text-dark" %>  </button>

<button type="button" class="btn btn-outline-info"><%= link_to t('g.back'), phone_numbers_path, class: "btn text-dark" %> </button>

app/views/phone_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("e.phone_numbers")%></h1>

<form method="GET" action="/phone_numbers">
  <div class="form-floating mb-3">
      <input type="number" name="filter" class="form-control" id="floatingInput"/>
      <label for="floatingInput"><%= t("phone_number.phone_numbers")%> </label>
  </div>
  <input type="submit" class="btn btn-primary" value=<%= t("g.search")%>  />
</form>
<br>

<table class="table table-hover table-bordered">
  <thead class="table-primary">
    <tr>
      <th><%=t('phone_number.phone_numbers') %></th>
      <th><%=t('phone_number.branch_office') %></th>
      <th colspan="3"><%=t('e.options') %></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.phone_number %></td>
        <td><%= phone_number.branch_office.address unless phone_number.nil? %></td>
        
        <% if user_signed_in? %>
          <% if current_user.admin? %>

              <td class="btn btn-info"><%= link_to t("g.show"), phone_number , class: "btn text-dark"%></td>
              <td class="btn btn-info"><%= link_to t("g.edit"), edit_phone_number_path(phone_number), class: "btn text-dark" %></td>
              <td class="btn btn-info"><%= link_to t("g.destroy"), phone_number, class: "btn text-dark", method: :delete, data: { confirm: t("g.are_you_sure") } %></td>
          <% else %>
            <td><%= "NO TIENES ACCESO" %></td>
          <% end %>
        <% end %>


      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @phone_numbers %>
<br>
<% if user_signed_in? %>
  <% if current_user.admin? %>
          <button type="button" class="btn btn-outline-secondary"><%= link_to t("e.new_phone_numbers"), new_phone_number_path, class: "btn text-dark" %></button>
      
  <% end %>
<% end %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>


<button type="button" class="btn btn-outline-primary"><%= link_to t('g.back'), phone_numbers_path, class: "btn text-dark" %></button>

app/views/phone_numbers/show.html.erb
<p id="notice" class="h6 text-sucess alert alert-primary" role="alert"><%= notice %></p>

<p class="form-control">
  <strong><%= t("phone_number.phone_numbers")%>:</strong>
  <%= @phone_number.phone_number %>
</p>

<p class="form-control">
  <strong><%= t("phone_number.branch_office")%>:</strong>
  <%= @phone_number.branch_office.address %>
</p>

<button type="button" class="btn btn-outline-info">
<%= link_to t('g.edit'), edit_phone_number_path(@phone_number), class: "btn text-dark" %> </button>

<button type="button" class="btn btn-outline-info"><%= link_to t('g.back'), phone_numbers_path , class: "btn text-dark"%> </button>